### ISSUE TITLE
Prepare to move repo to jefferislab organisation

### ISSUE THREAD

**Issue by jefferis** [SridharJagannathan/natverse#2]
We could keep track of main TODOs before this is ready for release

- [ ] Get some people to test it on different platforms
- [ ] Link to an overview documentation site

**Comment by jefferis** [comment]
I have also made a GitHub natverse organisation. I'm not sure that I want to use it to share all the packages, but it would give us the URL

https://natverse.github.io

which could be useful.

**Comment by SridharJagannathan** [comment]
Sure, will migrate the repo to this location.. :)

**Comment by jefferis** [comment]
- [ ] Integrated search across documentation
- [ ] Cheatsheet using core and extended functionality (e.g. fly specific)
- [ ] Maybe highlight google groups forum a bit more
- [ ] Simple shiny app that would allow you to upload a neuron and do some basic operations
